apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: study-app
  labels:
    app.kubernetes.io/name: study-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: study.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: study-app
                port:
                  number: 3001
